# Generated by Django 4.1.2 on 2023-04-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('product_name', models.TextField()),
                ('product_price', models.IntegerField()),
                ('product_country', models.TextField()),
                ('product_size', models.DecimalField(decimal_places=3, max_digits=4)),
                ('product_ABV', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
